### ISSUE TITLE
Run halts on random position

### ISSUE THREAD

**Issue by SimplyBG** [golismero/golismero#18]
Hello

I am running a freshly updated, very new version of Kali Debian Kali-Linux-2016.1-vbox-amd64 in a virtualbox using Oracle VM VirtualBox Manager 4.3.26.

I have used Golismero in the past and automated it with very good results using crontab midnight runs and then had custom scripts to collect up the reports.

It gets stuck on random positions, but mostly during Web Server Fingerprinting and SSLScan or sometimes Nmap. With 'get stuck' meaning that no more output is shown nor any other sign of life remains. The process is not terminated. It just does nothing for infinity (max tested 15 hours).

**This happens after just a simple:**
golismero scan <server ipadress> --brief --forbid-subdomains -d theharvester -o testoutput.txt

...but also with variations, such as without --brief, with various parts of it (-d) disabled (I've tried disabling theharvester, punkspider, openvas, dns etc) and aiming at a specific website address (my own web service) that has its address set in the Kali Debian's hostfile.  

Having added some custom code that runs Golismero process I can follow very closely system resources and exact timing of each output.**I stress however, that this occurs just running Golismero from the command line.**

```
#!/bin/bash

/root/pentest.sh | awk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0; fflush(); }' &

echo $!
$mypenprocess=$!

#pause x hours
sleep 21600  #6 hours
#sleep 60

#check if abc is running
kill -KILL $mypenprocess 2> /dev/null
```

After twenty runs, trying to disable various parts .. I cannot pinpoint a specific point of failure. I also monitor performance and disc space of the host OS (Windows 7) and nothing interesting on that side.

 /No, G isn't for Golismero.

**Comment by Gargo** [comment]
I have the same issue on the latest kali linux inside vmware

**Comment by andrewDeYoung** [comment]
I have the same issue as well, I really hope they patch it, seems like a great tool.
