### ISSUE TITLE
How to stop golismero without Ctrl-c?

### ISSUE THREAD

**Issue by chencoyote** [golismero/golismero#19]
Have anyway to stop golismero main process without ctrl-c?

When I use `kill -INT ${pid}` just main process was stop, subprocess still running...

**Comment by MarioVilas** [comment]
The process structure is basically something like this:

```
main process
\--- orchestrator process
     |-- worker process...
     |-- worker process...
     |-- worker process...
     \-- worker process...
```

Usually killing the main process kills everything, if that fails try the orchestrator process. May take a little while depending on what the worker processes are doing, if they're inside a blocking syscall they don't die, only when they try to talk to their parent process and realize it's dead.
