### ISSUE TITLE
How to write custom plugins, any plans for a Java wrapper ?

### ISSUE THREAD

**Issue by SyCode7** [golismero/golismero#21]
Hi, this is  a wonderful project. I have seen that there is an IDE for writing plugins, but how do I access the IDE, what are the steps for integrating/running custom plugins ..would there be some limitations ?
Lastly, is there a Java wrapper out there ....thanks.

**Comment by MarioVilas** [comment]
Hi! There is currently no Java wrapper, but in version 3.0 we plan to add multilanguage support.
