### ISSUE TITLE
No "Location" in report from demo plugin

### ISSUE THREAD

**Issue by aiddroid** [golismero/golismero#34]
I have wrote a demo plugin for backup file checking.This plugin works well for checking backup files, but the text report in console has no "Location" value. I have already checked my code, but found nothing.I'm new to Python from PHP, Pls help!

here is the core code in the plugin's run()
```python
        results = []
        # Check if backup file exists
        for f in self.test_files:
            for backup_ext in self.backup_extensions[:]:
                backup_url = 'http://' + info.hostname + '/' + f + backup_ext
                Logger.log_verbose("Testing %s..." % backup_url)
                response = HTTP.get_url(backup_url, method="HEAD")

                if response.status == "200":
                    Logger.log_verbose("Found backup :%s" % backup_url)
                    results.append(SuspiciousURL(URL(backup_url)))

        return results
```

**Comment by MarioVilas** [comment]
The text report is very limited and in practice only works for trying out the tool a bit. The HTML report format is a lot more complete. There are other formats like ReStructured Text which output the entire database as-is, those formats will definitely contain your Location information.
