### ISSUE TITLE
How to scan a POST request directly?

### ISSUE THREAD

**Issue by aiddroid** [golismero/golismero#35]
There's something wrong with sqlmap scanner.Even cannot detect a simple sql injection.Is there any way to scan a POST request directly?
```shell
python golismero.py 'http://localhost:8080/mysql.php' -a "sqlmap:args=--data 'username=allen'"
```

**Comment by cr0hn** [comment]
I'm sorry but, currently, is not possible

**Comment by aiddroid** [comment]
I have implemented it, thank you.

**Comment by MarioVilas** [comment]
Did you have to write a patch? In principle you can just pass any arguments to the plugin as you have described above, Golismero does nothing to interfere. Why did it not work for you?

**Comment by aiddroid** [comment]
No, I just added a --data arguemnt as --cookie

**Comment by MarioVilas** [comment]
Ah, I get it, cool :D

Would you like to send us a pull request?
