### ISSUE TITLE
How to use a profile?

### ISSUE THREAD

**Issue by trollmad3** [golismero/golismero#45]
I really love using golismero for pentesting but I have no idea how to use a profile. I want to use the profile `quick` but don't know. Please help!

![image](https://user-images.githubusercontent.com/7843719/40214853-59cdaf98-5a1a-11e8-9af5-93fa7c240507.png)

**Comment by trollmad3** [comment]
@MarioVilas I tried `--help` but found nothing about profiles.

**Comment by MarioVilas** [comment]
```
main options:
  -f FILE, --file FILE  load a list of targets from a plain text file
  --config FILE         global configuration file
  --user-config FILE    per-user configuration file
  -p NAME, --profile NAME
                        profile to use
```
