### ISSUE TITLE
output error, 

### ISSUE THREAD

**Issue by almosally** [golismero/golismero#55]
After scanning I can't generate a report, anyone got the same problem?
this mostly happened after scanning vulnerable website with > 10 vulnerabilities

![Capture](https://user-images.githubusercontent.com/31922369/73653265-19784e00-4689-11ea-94bc-73351fe0f968.JPG)

**Comment by almosally** [comment]
the command I use: python golismero.py scan "host" -o - -o "filename"

**Comment by MarioVilas** [comment]
I'm afraid I can't seem to reproduce the problem, are you using the version of Golismero that comes with Kali, or the latest one from Github?

**Comment by almosally** [comment]
Im using the one from Github

**Comment by MarioVilas** [comment]
What version of Python? If I recall correctly when this tool was developed we were using Python 2.7.3

**Comment by almosally** [comment]
I'm using python 2.7.16  it works well when I export report form database like first, I do :
python golismero.py scan "host" -db database.db"
then
python golismero.py import -db database.db  -o - -o "filename"

**Comment by MarioVilas** [comment]
That's odd, it should either always fail or never, splitting the scan and report into two distinct executions should not change anything at all...

**Comment by almosally** [comment]
I agree with you, any suggestions/recommendations?

**Comment by MarioVilas** [comment]
The only thing I can think of is try to diagnose the problem. I'd start by reproducing it reliably, then narrow it down by turning off plugins until the minimum plugin set is found that triggers the issue.

I'm guessing it's a type error but I've no idea why it happens only sometimes.

**Comment by almosally** [comment]
thanks alot
